# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adab8bd378fd0bfd487692ee07f989f7eb21a9791b33de8deca569dc1f46c25ccef4d8125790b50fa8b9f2bcf2eb3cb12ded7c9af9183af34608fbf27ce7e796

test:
  secret_key_base: 841a542776bc2134f40f4a5fdfc0068e5018c5755bd6df14bbae7d7b9dd85fa3b20a736a2822715eab9d22a37af9731940f1bf567c3e51ccebcc824bfd213bb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
